const ORDER_METADATA_PREFIX = "SCEUT_ORDER_METADATA::"

export type RecommendedPerfumeType = "primary" | "secondary" | "alternative"

export interface RecommendedPerfume {
  type: RecommendedPerfumeType
  label: string
  name: string
  number?: string
  brand?: string
  confidence?: number
  description?: string
  reasons?: string[]
  unitsLeft?: number
}

export interface OrderMetadata {
  manualNote?: string | null
  recommendedPerfumes?: RecommendedPerfume[]
  payment?: {
    merchantOrderNo?: string
    periodNo?: string
    status?: string
    authTime?: string
    authDate?: string
    authCode?: string
    respondCode?: string
    nextAuthDate?: string
    confirmedAt?: string
  }
  autoGenerated?: {
    source?: string
    subscriptionId?: string
    userId?: string
    targetPeriodNo?: string
    totalPeriods?: number | null
    targetPaymentDate?: string
    generatedAt?: string
  }
}

function isRecord(value: unknown): value is Record<string, any> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function normalizeMetadata(value: unknown): OrderMetadata {
  if (!isRecord(value)) {
    return {}
  }

  return {
    manualNote: typeof value.manualNote === "string" ? value.manualNote : null,
    recommendedPerfumes: Array.isArray(value.recommendedPerfumes) ? value.recommendedPerfumes : [],
    payment: isRecord(value.payment) ? value.payment : {},
    autoGenerated: isRecord(value.autoGenerated) ? value.autoGenerated : {},
  }
}

export function parseOrderMetadata(notes: unknown): OrderMetadata {
  if (typeof notes !== "string" || !notes.trim()) {
    return {}
  }

  const trimmed = notes.trim()

  if (!trimmed.startsWith(ORDER_METADATA_PREFIX)) {
    return {
      manualNote: trimmed,
      recommendedPerfumes: [],
      payment: {},
      autoGenerated: {},
    }
  }

  try {
    const parsed = JSON.parse(trimmed.slice(ORDER_METADATA_PREFIX.length))
    return normalizeMetadata(parsed)
  } catch {
    return {
      manualNote: trimmed,
      recommendedPerfumes: [],
      payment: {},
      autoGenerated: {},
    }
  }
}

export function getRecommendedPerfumes(notes: unknown): RecommendedPerfume[] {
  return parseOrderMetadata(notes).recommendedPerfumes || []
}

export function serializeOrderMetadata(notes: unknown, updates: Partial<OrderMetadata>): string {
  const existing = parseOrderMetadata(notes)

  const merged: OrderMetadata = {
    ...existing,
    ...updates,
    payment: {
      ...(existing.payment || {}),
      ...(updates.payment || {}),
    },
    autoGenerated: {
      ...(existing.autoGenerated || {}),
      ...(updates.autoGenerated || {}),
    },
    recommendedPerfumes: updates.recommendedPerfumes ?? existing.recommendedPerfumes ?? [],
  }

  return `${ORDER_METADATA_PREFIX}${JSON.stringify(merged)}`
}

export function buildRecommendedPerfumes(recommendations: Record<string, any> | null | undefined): RecommendedPerfume[] {
  if (!recommendations) {
    return []
  }

  const labels: Record<RecommendedPerfumeType, string> = {
    primary: "主要推薦",
    secondary: "次要推薦",
    alternative: "替代推薦",
  }

  const orderedTypes: RecommendedPerfumeType[] = ["primary", "secondary", "alternative"]

  return orderedTypes.flatMap((type) => {
    const item = recommendations[type]
    if (!item?.name) {
      return []
    }

    return [{
      type,
      label: labels[type],
      name: item.name,
      number: item.number || "",
      brand: item.brand || "",
      confidence: typeof item.confidence === "number" ? item.confidence : undefined,
      description: item.description || "",
      reasons: Array.isArray(item.reasons) ? item.reasons : [],
      unitsLeft: typeof item.unitsLeft === "number" ? item.unitsLeft : undefined,
    }]
  })
}
