import { createClient } from "@supabase/supabase-js"
import { parseOrderMetadata, serializeOrderMetadata } from "@/lib/order-metadata"
import type { ParsedNewebPayEmail } from "@/lib/newebpay-email-parser"

const supabaseUrl =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  "https://bbrnbyzjmxgxnczzymdt.supabase.co"

const supabaseKey =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicm5ieXpqbXhneG5jenp5bWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQ3ODcsImV4cCI6MjA2MDYyMDc4N30.S5BFoAq6idmTKLwGYa0bhxFVEoEmQ3voshyX03FVe0Y"

const supabase = createClient(supabaseUrl, supabaseKey)

export type PaymentSyncResult = {
  status: "updated" | "updated_subscriber_only" | "skipped_no_match" | "dry_run"
  subscriberId?: string | number
  orderId?: string
  merchantOrderNo: string
  periodNo: string
  message: string
}

function buildEmailEvent(parsed: ParsedNewebPayEmail) {
  return {
    received_at: new Date().toISOString(),
    source: "gmail_poll",
    gmail_message_id: parsed.gmailMessageId,
    merchant_order_no: parsed.merchantOrderNo,
    period_no: parsed.periodNo,
    result_text: parsed.resultText || null,
    auth_code: parsed.authCode || null,
    auth_date: parsed.authDateIso || parsed.authDateText || null,
    next_auth_date: parsed.nextAuthDateIso || parsed.nextAuthDateText || null,
    trade_no: parsed.tradeNo || null,
    amount: parsed.amount ?? null,
    next_amount: parsed.nextAmount ?? null,
    current_period: parsed.currentPeriod ?? null,
    total_periods: parsed.totalPeriods ?? null,
    success: parsed.isSuccess,
    raw_text: parsed.rawText,
  }
}

function appendEmailEvent(existingPaymentData: any, parsed: ParsedNewebPayEmail) {
  const existingEvents = Array.isArray(existingPaymentData?.gmail_events)
    ? existingPaymentData.gmail_events
    : []

  return [...existingEvents, buildEmailEvent(parsed)].slice(-30)
}

function resolveSubscriptionStatus(parsed: ParsedNewebPayEmail, currentStatus?: string | null) {
  if (parsed.isSuccess && parsed.totalPeriods && parsed.currentPeriod) {
    return parsed.currentPeriod >= parsed.totalPeriods ? "completed" : "active"
  }

  return currentStatus || "active"
}

async function findSubscriber(parsed: ParsedNewebPayEmail) {
  if (parsed.periodNo) {
    const direct = await supabase
      .from("subscribers")
      .select("*")
      .eq("period_no", parsed.periodNo)
      .maybeSingle()

    if (direct.data) {
      return direct.data
    }
  }

  if (parsed.merchantOrderNo) {
    const fallback = await supabase
      .from("subscribers")
      .select("*")
      .eq("merchant_order_no", parsed.merchantOrderNo)
      .maybeSingle()

    if (fallback.data) {
      return fallback.data
    }
  }

  return null
}

async function findMatchingOrder(subscriber: any, parsed: ParsedNewebPayEmail) {
  let query = supabase
    .from("orders")
    .select("id, notes, order_status, user_id, customer_email, updated_at")
    .order("created_at", { ascending: false })
    .limit(30)

  if (subscriber?.user_id) {
    query = query.eq("user_id", subscriber.user_id)
  } else if (subscriber?.email) {
    query = query.eq("customer_email", subscriber.email)
  } else {
    return null
  }

  const { data, error } = await query
  if (error) {
    throw error
  }

  return (data || []).find((order) => {
    const metadata = parseOrderMetadata(order.notes)
    const matchesMerchantOrderNo = metadata.payment?.merchantOrderNo === parsed.merchantOrderNo
    const matchesPeriodNo =
      metadata.payment?.periodNo === parsed.periodNo ||
      metadata.autoGenerated?.targetPeriodNo === parsed.periodNo

    return matchesMerchantOrderNo && matchesPeriodNo
  }) || null
}

async function updateSubscriber(subscriber: any, parsed: ParsedNewebPayEmail, dryRun: boolean) {
  const paymentData = typeof subscriber.payment_data === "string"
    ? (() => {
        try {
          return JSON.parse(subscriber.payment_data)
        } catch {
          return {}
        }
      })()
    : (subscriber.payment_data || {})

  const nextPaymentData = {
    ...paymentData,
    merchant_order_no: subscriber.merchant_order_no || parsed.merchantOrderNo,
    last_auth_date: parsed.authDateText || paymentData.last_auth_date || null,
    last_auth_date_iso: parsed.authDateIso || paymentData.last_auth_date_iso || null,
    last_auth_amount: parsed.amount ?? paymentData.last_auth_amount ?? null,
    last_auth_code: parsed.authCode || paymentData.last_auth_code || null,
    last_trade_no: parsed.tradeNo || paymentData.last_trade_no || null,
    already_times: parsed.currentPeriod ?? paymentData.already_times ?? null,
    total_times: parsed.totalPeriods ?? paymentData.total_times ?? null,
    respond_code: parsed.bankResponseCode || paymentData.respond_code || null,
    next_auth_date: parsed.nextAuthDateText || paymentData.next_auth_date || null,
    gmail_events: appendEmailEvent(paymentData, parsed),
  }

  const updatePayload: Record<string, any> = {
    payment_status: parsed.isSuccess ? "paid" : "failed",
    subscription_status: resolveSubscriptionStatus(parsed, subscriber.subscription_status),
    updated_at: new Date().toISOString(),
    payment_data: nextPaymentData,
  }

  if (parsed.isSuccess && parsed.authDateIso) {
    updatePayload.last_payment_date = parsed.authDateIso
  }

  if (parsed.nextAuthDateIso) {
    updatePayload.next_payment_date = parsed.nextAuthDateIso
  }

  if (parsed.amount) {
    updatePayload.monthly_fee = parsed.amount
  }

  if (!dryRun) {
    const { error } = await supabase
      .from("subscribers")
      .update(updatePayload)
      .eq("id", subscriber.id)

    if (error) {
      throw error
    }
  }

  return updatePayload
}

async function updateOrder(order: any, parsed: ParsedNewebPayEmail, dryRun: boolean) {
  const notes = serializeOrderMetadata(order.notes, {
    payment: {
      merchantOrderNo: parsed.merchantOrderNo,
      periodNo: parsed.periodNo,
      status: parsed.isSuccess ? "charge_confirmed" : "charge_failed",
      authDate: parsed.authDateText || parsed.authDateIso,
      authCode: parsed.authCode,
      respondCode: parsed.bankResponseCode,
      nextAuthDate: parsed.nextAuthDateText || parsed.nextAuthDateIso,
      confirmedAt: parsed.isSuccess ? new Date().toISOString() : undefined,
    },
  })

  const updatePayload: Record<string, any> = {
    notes,
    updated_at: new Date().toISOString(),
  }

  if (parsed.isSuccess && order.order_status !== "confirmed") {
    updatePayload.order_status = "confirmed"
  }

  if (!dryRun) {
    const { error } = await supabase
      .from("orders")
      .update(updatePayload)
      .eq("id", order.id)

    if (error) {
      throw error
    }
  }

  return updatePayload
}

export async function syncPaymentEmail(parsed: ParsedNewebPayEmail, options?: { dryRun?: boolean }): Promise<PaymentSyncResult> {
  const dryRun = Boolean(options?.dryRun)
  const subscriber = await findSubscriber(parsed)

  if (!subscriber) {
    return {
      status: "skipped_no_match",
      merchantOrderNo: parsed.merchantOrderNo,
      periodNo: parsed.periodNo,
      message: "No matching subscriber found",
    }
  }

  await updateSubscriber(subscriber, parsed, dryRun)

  const matchedOrder = await findMatchingOrder(subscriber, parsed)
  if (!matchedOrder) {
    return {
      status: dryRun ? "dry_run" : "updated_subscriber_only",
      subscriberId: subscriber.id,
      merchantOrderNo: parsed.merchantOrderNo,
      periodNo: parsed.periodNo,
      message: "Subscriber updated but no matching generated order found",
    }
  }

  await updateOrder(matchedOrder, parsed, dryRun)

  return {
    status: dryRun ? "dry_run" : "updated",
    subscriberId: subscriber.id,
    orderId: matchedOrder.id,
    merchantOrderNo: parsed.merchantOrderNo,
    periodNo: parsed.periodNo,
    message: dryRun
      ? "Dry run matched subscriber and order"
      : "Subscriber and matching order updated successfully",
  }
}
